<?php

namespace Database\Seeders;

use App\Models\Exercise;
use App\Models\EquipmentType;
use App\Models\MuscleGroup;
use Illuminate\Database\Seeder;

class ExerciseSeeder extends Seeder
{
    public function run(): void
    {
        $muscleGroups = MuscleGroup::all()->keyBy('name');
        $equipment = EquipmentType::all()->keyBy('name');

        $exercises = [
            // ========== CHEST ==========
            [
                'name' => 'Push-up',
                'name_es' => 'Flexión de brazos',
                'description' => 'Classic bodyweight chest exercise',
                'description_es' => 'Ejercicio clásico de pecho con peso corporal. Mantén el cuerpo recto como una tabla.',
                'primary_muscle_group' => 'Chest',
                'muscle_groups' => ['Chest', 'Triceps', 'Shoulders'],
                'equipment' => 'Bodyweight',
                'difficulty' => 'beginner',
                'location_type' => 'both',
                'exercise_type' => 'strength',
                'calories_per_minute' => 7.5,
                'met_value' => 8.0,
                'is_compound' => true,
                'instructions' => [
                    'Colócate en posición de tabla con las manos ligeramente más separadas que los hombros',
                    'Mantén el cuerpo recto desde la cabeza hasta los talones',
                    'Baja el pecho hasta casi tocar el suelo doblando los codos',
                    'Empuja hacia arriba hasta extender los brazos completamente',
                    'Repite el movimiento controlando tanto la bajada como la subida',
                ],
                'tips' => [
                    'Aprieta el core durante todo el ejercicio',
                    'No dejes caer las caderas ni elevarlas demasiado',
                    'Si es muy difícil, hazlo sobre las rodillas',
                ],
                'tags' => ['pecho', 'triceps', 'hombros', 'cuerpo completo', 'sin equipo'],
            ],
            [
                'name' => 'Bench Press',
                'name_es' => 'Press de banca',
                'description' => 'Barbell chest press on flat bench',
                'description_es' => 'Press de banca plano con barra olímpica. El ejercicio rey para el pecho.',
                'primary_muscle_group' => 'Chest',
                'muscle_groups' => ['Chest', 'Triceps', 'Shoulders'],
                'equipment' => 'Barbell',
                'difficulty' => 'intermediate',
                'location_type' => 'gym',
                'exercise_type' => 'strength',
                'calories_per_minute' => 9.0,
                'met_value' => 6.0,
                'is_compound' => true,
                'instructions' => [
                    'Túmbate en el banco con los pies planos en el suelo',
                    'Agarra la barra con un agarre ligeramente más ancho que los hombros',
                    'Desraquea la barra y colócala sobre el pecho',
                    'Baja la barra de forma controlada hasta rozar el pecho',
                    'Empuja la barra hacia arriba hasta la extensión completa de los brazos',
                ],
                'tips' => [
                    'Arquea ligeramente la espalda baja manteniendo los omóplatos juntos',
                    'Los pies deben presionar el suelo en todo momento',
                    'Usa siempre un compañero de entrenamiento para pesos pesados',
                ],
                'tags' => ['pecho', 'banca', 'barra', 'compuesto', 'gym'],
            ],
            [
                'name' => 'Dumbbell Fly',
                'name_es' => 'Aperturas con mancuernas',
                'description' => 'Chest isolation exercise with dumbbells',
                'description_es' => 'Ejercicio de aislamiento de pecho con mancuernas para mayor rango de movimiento.',
                'primary_muscle_group' => 'Chest',
                'muscle_groups' => ['Chest'],
                'equipment' => 'Dumbbells',
                'difficulty' => 'intermediate',
                'location_type' => 'both',
                'exercise_type' => 'strength',
                'calories_per_minute' => 6.0,
                'met_value' => 5.0,
                'is_compound' => false,
                'instructions' => [
                    'Túmbate en el banco con una mancuerna en cada mano',
                    'Extiende los brazos sobre el pecho con una ligera flexión de codos',
                    'Abre los brazos lentamente hacia los lados en arco hasta sentir el estiramiento en el pecho',
                    'Vuelve a la posición inicial juntando las mancuernas arriba',
                ],
                'tips' => [
                    'Mantén una ligera flexión en los codos durante todo el movimiento',
                    'Controla la bajada para evitar lesiones en los hombros',
                    'No uses peso excesivo en este ejercicio de aislamiento',
                ],
                'tags' => ['pecho', 'mancuernas', 'aislamiento'],
            ],
            [
                'name' => 'Diamond Push-up',
                'name_es' => 'Flexión en diamante',
                'description' => 'Narrow grip push-up targeting triceps and inner chest',
                'description_es' => 'Flexión con agarre estrecho en forma de diamante para tríceps y pecho interno.',
                'primary_muscle_group' => 'Triceps',
                'muscle_groups' => ['Triceps', 'Chest'],
                'equipment' => 'Bodyweight',
                'difficulty' => 'intermediate',
                'location_type' => 'both',
                'exercise_type' => 'strength',
                'calories_per_minute' => 8.0,
                'met_value' => 8.0,
                'is_compound' => true,
                'instructions' => [
                    'Colócate en posición de flexión con las manos juntas formando un triángulo',
                    'Los pulgares e índices deben tocarse formando un diamante',
                    'Baja el pecho hacia las manos manteniendo los codos cerca del cuerpo',
                    'Empuja hacia arriba hasta la extensión completa',
                ],
                'tips' => [
                    'Mantén el cuerpo completamente recto',
                    'Los codos deben moverse hacia atrás, no hacia los lados',
                ],
                'tags' => ['triceps', 'pecho', 'sin equipo', 'casa'],
            ],

            // ========== BACK ==========
            [
                'name' => 'Pull-up',
                'name_es' => 'Dominada',
                'description' => 'Classic vertical pulling exercise using a pull-up bar',
                'description_es' => 'Ejercicio fundamental de tracción vertical con barra de dominadas.',
                'primary_muscle_group' => 'Lats',
                'muscle_groups' => ['Lats', 'Back', 'Biceps'],
                'equipment' => 'Pull-up Bar',
                'difficulty' => 'intermediate',
                'location_type' => 'both',
                'exercise_type' => 'strength',
                'calories_per_minute' => 9.0,
                'met_value' => 8.0,
                'is_compound' => true,
                'instructions' => [
                    'Agarra la barra con un agarre prono (palmas hacia afuera) al ancho de los hombros',
                    'Cuelga con los brazos completamente extendidos',
                    'Tira hacia arriba llevando el pecho hacia la barra',
                    'Baja de forma controlada hasta la extensión completa',
                ],
                'tips' => [
                    'Inicia el movimiento retrayendo las escápulas',
                    'Evita el balanceo del cuerpo',
                    'Si no puedes hacer ninguna, usa una banda elástica de ayuda',
                ],
                'tags' => ['espalda', 'dorsales', 'biceps', 'barra', 'peso corporal'],
            ],
            [
                'name' => 'Deadlift',
                'name_es' => 'Peso muerto',
                'description' => 'The king of compound exercises for posterior chain',
                'description_es' => 'El rey de los ejercicios compuestos para la cadena posterior. Trabaja espalda, glúteos e isquiotibiales.',
                'primary_muscle_group' => 'Back',
                'muscle_groups' => ['Back', 'Glutes', 'Hamstrings', 'Forearms'],
                'equipment' => 'Barbell',
                'difficulty' => 'intermediate',
                'location_type' => 'gym',
                'exercise_type' => 'strength',
                'calories_per_minute' => 10.0,
                'met_value' => 6.0,
                'is_compound' => true,
                'instructions' => [
                    'Coloca la barra sobre el suelo y párate con los pies al ancho de caderas',
                    'Agarra la barra con agarre prono o mixto, manos al ancho de hombros',
                    'Mantén la espalda recta y el pecho elevado',
                    'Empuja el suelo con los pies mientras levantas la barra pegada a las piernas',
                    'Extiende las caderas y las rodillas simultáneamente hasta la posición erguida',
                    'Baja la barra de forma controlada manteniendo la espalda neutra',
                ],
                'tips' => [
                    'NUNCA redondees la espalda baja con cargas pesadas',
                    'La barra debe rozar las espinillas durante el levantamiento',
                    'Aprieta los glúteos en la posición superior',
                ],
                'tags' => ['espalda', 'cadena posterior', 'gluteos', 'isquiotibiales', 'barra'],
            ],
            [
                'name' => 'Bent-over Row',
                'name_es' => 'Remo inclinado con barra',
                'description' => 'Horizontal pulling exercise for back thickness',
                'description_es' => 'Ejercicio de tracción horizontal para dar grosor a la espalda.',
                'primary_muscle_group' => 'Back',
                'muscle_groups' => ['Back', 'Lats', 'Biceps', 'Trapezius'],
                'equipment' => 'Barbell',
                'difficulty' => 'intermediate',
                'location_type' => 'gym',
                'exercise_type' => 'strength',
                'calories_per_minute' => 8.5,
                'met_value' => 6.0,
                'is_compound' => true,
                'instructions' => [
                    'Párate con los pies al ancho de hombros, flexiona la cadera hasta 45 grados',
                    'Agarra la barra con agarre prono ligeramente más amplio que los hombros',
                    'Mantén la espalda recta y paralela al suelo',
                    'Tira de la barra hacia el abdomen retrayendo las escápulas',
                    'Baja la barra de forma controlada hasta la extensión completa',
                ],
                'tips' => [
                    'Mantén la espalda baja neutra en todo momento',
                    'No uses el impulso del torso para levantar el peso',
                ],
                'tags' => ['espalda', 'remo', 'barra', 'grosor'],
            ],
            [
                'name' => 'Lat Pulldown',
                'name_es' => 'Jalón al pecho',
                'description' => 'Cable machine exercise for lat development',
                'description_es' => 'Ejercicio con polea para desarrollar los dorsales. Alternativa a las dominadas.',
                'primary_muscle_group' => 'Lats',
                'muscle_groups' => ['Lats', 'Back', 'Biceps'],
                'equipment' => 'Cable Machine',
                'difficulty' => 'beginner',
                'location_type' => 'gym',
                'exercise_type' => 'strength',
                'calories_per_minute' => 7.0,
                'met_value' => 5.5,
                'is_compound' => true,
                'instructions' => [
                    'Siéntate en la máquina con los muslos asegurados bajo los apoyos',
                    'Agarra la barra con un agarre prono más ancho que los hombros',
                    'Jala la barra hacia el pecho mientras arqueas ligeramente la espalda',
                    'Contrae los dorsales en la posición inferior',
                    'Sube la barra de forma controlada hasta la extensión completa',
                ],
                'tips' => [
                    'Lleva los codos hacia abajo y atrás, no hacia los lados',
                    'Evita usar demasiado impulso',
                ],
                'tags' => ['dorsales', 'espalda', 'jalón', 'polea'],
            ],

            // ========== SHOULDERS ==========
            [
                'name' => 'Overhead Press',
                'name_es' => 'Press militar',
                'description' => 'Standing barbell press for shoulder development',
                'description_es' => 'Press por encima de la cabeza de pie con barra. Ejercicio fundamental de hombros.',
                'primary_muscle_group' => 'Shoulders',
                'muscle_groups' => ['Shoulders', 'Triceps', 'Trapezius'],
                'equipment' => 'Barbell',
                'difficulty' => 'intermediate',
                'location_type' => 'gym',
                'exercise_type' => 'strength',
                'calories_per_minute' => 8.0,
                'met_value' => 6.0,
                'is_compound' => true,
                'instructions' => [
                    'Párate con los pies al ancho de hombros, agarra la barra con agarre prono',
                    'Coloca la barra a la altura de la clavícula con los codos hacia adelante',
                    'Empuja la barra verticalmente sobre la cabeza extendiendo los brazos',
                    'Mete la cabeza ligeramente atrás para que la barra pase cerca de la cara',
                    'Baja la barra de forma controlada de vuelta a la posición inicial',
                ],
                'tips' => [
                    'Aprieta el core y los glúteos durante todo el movimiento',
                    'La barra debe seguir una trayectoria vertical sobre el centro de gravedad',
                ],
                'tags' => ['hombros', 'press militar', 'barra', 'compuesto'],
            ],
            [
                'name' => 'Lateral Raise',
                'name_es' => 'Elevaciones laterales',
                'description' => 'Dumbbell isolation exercise for side deltoids',
                'description_es' => 'Ejercicio de aislamiento para el deltoides lateral con mancuernas.',
                'primary_muscle_group' => 'Shoulders',
                'muscle_groups' => ['Shoulders'],
                'equipment' => 'Dumbbells',
                'difficulty' => 'beginner',
                'location_type' => 'both',
                'exercise_type' => 'strength',
                'calories_per_minute' => 5.0,
                'met_value' => 4.0,
                'is_compound' => false,
                'instructions' => [
                    'Párate con los pies al ancho de hombros, una mancuerna en cada mano',
                    'Con los brazos ligeramente flexionados, eleva las mancuernas hacia los lados',
                    'Sube hasta que los brazos estén paralelos al suelo',
                    'Baja de forma controlada sin dejar caer las mancuernas',
                ],
                'tips' => [
                    'No eleves los hombros hacia las orejas',
                    'Usa menos peso del que crees necesitar al principio',
                    'El movimiento debe iniciar desde el hombro, no desde la muñeca',
                ],
                'tags' => ['hombros', 'deltoides lateral', 'mancuernas', 'aislamiento'],
            ],

            // ========== LEGS ==========
            [
                'name' => 'Squat',
                'name_es' => 'Sentadilla',
                'description' => 'Fundamental lower body compound exercise',
                'description_es' => 'La reina de los ejercicios de tren inferior. Ejercicio compuesto fundamental para cuádriceps, glúteos e isquiotibiales.',
                'primary_muscle_group' => 'Quadriceps',
                'muscle_groups' => ['Quadriceps', 'Glutes', 'Hamstrings'],
                'equipment' => 'Barbell',
                'difficulty' => 'intermediate',
                'location_type' => 'gym',
                'exercise_type' => 'strength',
                'calories_per_minute' => 10.0,
                'met_value' => 6.0,
                'is_compound' => true,
                'instructions' => [
                    'Coloca la barra sobre los trapecios y párate con los pies al ancho de hombros',
                    'Los pies ligeramente girados hacia afuera (15-30 grados)',
                    'Baja flexionando caderas y rodillas manteniendo el pecho elevado',
                    'Desciende hasta que los muslos estén paralelos al suelo o más abajo',
                    'Sube empujando el suelo con los pies hasta la posición inicial',
                ],
                'tips' => [
                    'Las rodillas deben seguir la dirección de los pies',
                    'Mantén el peso en los talones y mitad del pie',
                    'No dejes que las rodillas colapsen hacia dentro',
                ],
                'tags' => ['cuadriceps', 'gluteos', 'isquiotibiales', 'barra', 'tren inferior'],
            ],
            [
                'name' => 'Bodyweight Squat',
                'name_es' => 'Sentadilla libre',
                'description' => 'Squat without added weight for beginners',
                'description_es' => 'Sentadilla con peso corporal, ideal para principiantes y para hacer en casa.',
                'primary_muscle_group' => 'Quadriceps',
                'muscle_groups' => ['Quadriceps', 'Glutes', 'Hamstrings'],
                'equipment' => 'Bodyweight',
                'difficulty' => 'beginner',
                'location_type' => 'both',
                'exercise_type' => 'strength',
                'calories_per_minute' => 7.5,
                'met_value' => 5.0,
                'is_compound' => true,
                'instructions' => [
                    'Párate con los pies al ancho de hombros o ligeramente más abiertos',
                    'Los pies ligeramente girados hacia afuera',
                    'Baja como si fueras a sentarte en una silla, manteniendo el pecho elevado',
                    'Baja hasta que los muslos estén paralelos al suelo',
                    'Sube empujando con los talones',
                ],
                'tips' => [
                    'Mira hacia adelante durante todo el movimiento',
                    'Si te cuesta mantener el equilibrio, eleva ligeramente los talones',
                ],
                'tags' => ['cuadriceps', 'gluteos', 'sin equipo', 'casa', 'principiante'],
            ],
            [
                'name' => 'Lunge',
                'name_es' => 'Zancada',
                'description' => 'Single-leg exercise for leg strength and balance',
                'description_es' => 'Ejercicio unilateral para la fuerza de piernas y el equilibrio.',
                'primary_muscle_group' => 'Quadriceps',
                'muscle_groups' => ['Quadriceps', 'Glutes', 'Hamstrings'],
                'equipment' => 'Bodyweight',
                'difficulty' => 'beginner',
                'location_type' => 'both',
                'exercise_type' => 'strength',
                'calories_per_minute' => 7.0,
                'met_value' => 5.5,
                'is_compound' => true,
                'instructions' => [
                    'Párate erguido con los pies juntos',
                    'Da un paso adelante con una pierna bajando la rodilla trasera hacia el suelo',
                    'La rodilla delantera debe estar alineada sobre el tobillo',
                    'Baja hasta que la rodilla trasera casi toque el suelo',
                    'Empuja con el talón delantero para volver a la posición inicial',
                ],
                'tips' => [
                    'Mantén el torso erguido durante todo el movimiento',
                    'El paso debe ser suficientemente largo para que la rodilla delantera no sobrepase el pie',
                ],
                'tags' => ['cuadriceps', 'gluteos', 'unilateral', 'equilibrio', 'casa'],
            ],
            [
                'name' => 'Romanian Deadlift',
                'name_es' => 'Peso muerto rumano',
                'description' => 'Hip hinge exercise targeting hamstrings and glutes',
                'description_es' => 'Peso muerto con énfasis en el estiramiento de isquiotibiales y activación de glúteos.',
                'primary_muscle_group' => 'Hamstrings',
                'muscle_groups' => ['Hamstrings', 'Glutes', 'Back'],
                'equipment' => 'Barbell',
                'difficulty' => 'intermediate',
                'location_type' => 'gym',
                'exercise_type' => 'strength',
                'calories_per_minute' => 8.5,
                'met_value' => 6.0,
                'is_compound' => true,
                'instructions' => [
                    'Párate con los pies al ancho de caderas, agarra la barra con agarre prono',
                    'Mantén las rodillas ligeramente flexionadas',
                    'Inclina el torso hacia adelante manteniendo la espalda recta',
                    'Baja la barra pegada a las piernas sintiendo el estiramiento en los isquiotibiales',
                    'Vuelve a la posición inicial activando los glúteos',
                ],
                'tips' => [
                    'La espalda siempre debe mantenerse recta, sin redondeo',
                    'El movimiento debe iniciar desde la cadera, no desde la espalda',
                ],
                'tags' => ['isquiotibiales', 'gluteos', 'peso muerto', 'barra'],
            ],
            [
                'name' => 'Glute Bridge',
                'name_es' => 'Puente de glúteos',
                'description' => 'Hip thrust variation for glute development',
                'description_es' => 'Ejercicio fundamental para activar y desarrollar los glúteos.',
                'primary_muscle_group' => 'Glutes',
                'muscle_groups' => ['Glutes', 'Hamstrings'],
                'equipment' => 'Bodyweight',
                'difficulty' => 'beginner',
                'location_type' => 'both',
                'exercise_type' => 'strength',
                'calories_per_minute' => 5.0,
                'met_value' => 4.0,
                'is_compound' => false,
                'instructions' => [
                    'Túmbate boca arriba con las rodillas flexionadas y los pies planos en el suelo',
                    'Los brazos a los lados del cuerpo, palmas hacia abajo',
                    'Empuja con los talones elevando las caderas hacia el techo',
                    'Aprieta los glúteos en la posición superior y mantén 1-2 segundos',
                    'Baja de forma controlada',
                ],
                'tips' => [
                    'Los pies deben estar a la distancia justa para que las rodillas formen 90 grados',
                    'Empuja con los talones, no con los dedos del pie',
                ],
                'tags' => ['gluteos', 'isquiotibiales', 'sin equipo', 'casa', 'principiante'],
            ],
            [
                'name' => 'Hip Thrust',
                'name_es' => 'Empuje de cadera',
                'description' => 'Best glute exercise with barbell',
                'description_es' => 'El mejor ejercicio para desarrollar los glúteos. Con barra y banco.',
                'primary_muscle_group' => 'Glutes',
                'muscle_groups' => ['Glutes', 'Hamstrings'],
                'equipment' => 'Barbell',
                'difficulty' => 'intermediate',
                'location_type' => 'gym',
                'exercise_type' => 'strength',
                'calories_per_minute' => 7.0,
                'met_value' => 5.5,
                'is_compound' => false,
                'instructions' => [
                    'Apoya la parte superior de la espalda en el banco con los hombros sobre el borde',
                    'Coloca la barra sobre las caderas con un amortiguador',
                    'Los pies deben estar planos en el suelo, rodillas a 90 grados',
                    'Empuja las caderas hacia arriba hasta la extensión completa',
                    'Aprieta los glúteos en la posición superior',
                ],
                'tips' => [
                    'Usa un amortiguador o toalla para proteger las caderas',
                    'La barbilla debe estar metida hacia el pecho',
                ],
                'tags' => ['gluteos', 'barra', 'banco'],
            ],
            [
                'name' => 'Calf Raise',
                'name_es' => 'Elevación de talones',
                'description' => 'Isolation exercise for calf muscles',
                'description_es' => 'Ejercicio de aislamiento para los gemelos y sóleo.',
                'primary_muscle_group' => 'Calves',
                'muscle_groups' => ['Calves'],
                'equipment' => 'Bodyweight',
                'difficulty' => 'beginner',
                'location_type' => 'both',
                'exercise_type' => 'strength',
                'calories_per_minute' => 4.0,
                'met_value' => 3.5,
                'is_compound' => false,
                'instructions' => [
                    'Párate con los pies al ancho de caderas, los talones en el borde de un escalón',
                    'Baja los talones todo lo posible para estirar los gemelos',
                    'Eleva en puntillas lo máximo posible',
                    'Mantén 1 segundo en la posición superior',
                    'Baja de forma controlada',
                ],
                'tips' => [
                    'Usa la punta de los pies ligeramente hacia afuera para trabajar diferentes partes',
                    'Hazlo en escalón para mayor rango de movimiento',
                ],
                'tags' => ['gemelos', 'tobillo', 'sin equipo'],
            ],

            // ========== BICEPS ==========
            [
                'name' => 'Barbell Curl',
                'name_es' => 'Curl de bíceps con barra',
                'description' => 'Classic barbell bicep curl',
                'description_es' => 'El ejercicio clásico para el bíceps con barra recta o Z.',
                'primary_muscle_group' => 'Biceps',
                'muscle_groups' => ['Biceps', 'Forearms'],
                'equipment' => 'Barbell',
                'difficulty' => 'beginner',
                'location_type' => 'gym',
                'exercise_type' => 'strength',
                'calories_per_minute' => 5.5,
                'met_value' => 4.5,
                'is_compound' => false,
                'instructions' => [
                    'Párate con los pies al ancho de hombros, agarra la barra con agarre supino',
                    'Los codos pegados a los lados del cuerpo',
                    'Flexiona los codos subiendo la barra hacia los hombros',
                    'Aprieta el bíceps en la posición superior',
                    'Baja de forma controlada hasta la extensión completa',
                ],
                'tips' => [
                    'No uses el impulso del torso para subir el peso',
                    'Mantén los codos fijos a los lados',
                ],
                'tags' => ['biceps', 'barra', 'curl'],
            ],
            [
                'name' => 'Hammer Curl',
                'name_es' => 'Curl martillo',
                'description' => 'Neutral grip curl targeting brachialis and biceps',
                'description_es' => 'Curl con agarre neutro para trabajar el braquial y bíceps.',
                'primary_muscle_group' => 'Biceps',
                'muscle_groups' => ['Biceps', 'Forearms'],
                'equipment' => 'Dumbbells',
                'difficulty' => 'beginner',
                'location_type' => 'both',
                'exercise_type' => 'strength',
                'calories_per_minute' => 5.0,
                'met_value' => 4.0,
                'is_compound' => false,
                'instructions' => [
                    'De pie con una mancuerna en cada mano, agarre neutro (pulgares arriba)',
                    'Los codos pegados a los lados',
                    'Sube las mancuernas hacia los hombros manteniendo el agarre neutro',
                    'Baja de forma controlada',
                ],
                'tips' => [
                    'No rotes la muñeca durante el movimiento',
                    'Puedes hacerlo alternando brazos',
                ],
                'tags' => ['biceps', 'mancuernas', 'curl martillo'],
            ],

            // ========== TRICEPS ==========
            [
                'name' => 'Tricep Dip',
                'name_es' => 'Fondos de tríceps',
                'description' => 'Bodyweight tricep exercise using parallel bars or bench',
                'description_es' => 'Ejercicio de tríceps con peso corporal en barras paralelas o banco.',
                'primary_muscle_group' => 'Triceps',
                'muscle_groups' => ['Triceps', 'Chest', 'Shoulders'],
                'equipment' => 'Parallel Bars',
                'difficulty' => 'intermediate',
                'location_type' => 'gym',
                'exercise_type' => 'strength',
                'calories_per_minute' => 8.0,
                'met_value' => 6.0,
                'is_compound' => true,
                'instructions' => [
                    'Agarra las barras paralelas con las palmas hacia dentro',
                    'Levanta el cuerpo y extiende los brazos completamente',
                    'Baja el cuerpo flexionando los codos hasta los 90 grados',
                    'Empuja hacia arriba hasta la extensión completa',
                ],
                'tips' => [
                    'Mantén el torso ligeramente inclinado hacia adelante para más énfasis en el pecho',
                    'Cuerpo más vertical = más énfasis en tríceps',
                ],
                'tags' => ['triceps', 'pecho', 'fondos', 'peso corporal'],
            ],
            [
                'name' => 'Skull Crusher',
                'name_es' => 'Extensión de tríceps en banco',
                'description' => 'Lying tricep extension with barbell',
                'description_es' => 'Extensión de tríceps tumbado con barra. Ejercicio de aislamiento para tríceps.',
                'primary_muscle_group' => 'Triceps',
                'muscle_groups' => ['Triceps'],
                'equipment' => 'Barbell',
                'difficulty' => 'intermediate',
                'location_type' => 'gym',
                'exercise_type' => 'strength',
                'calories_per_minute' => 6.0,
                'met_value' => 4.5,
                'is_compound' => false,
                'instructions' => [
                    'Túmbate en el banco, agarra la barra con agarre prono al ancho de hombros',
                    'Extiende los brazos perpendicularmente al torso',
                    'Baja la barra hacia la frente flexionando solo los codos',
                    'Los codos deben mantenerse fijos, apuntando al techo',
                    'Extiende los codos volviendo a la posición inicial',
                ],
                'tips' => [
                    'No dejes que los codos se abran hacia los lados',
                    'Usa un peso moderado para proteger los codos',
                ],
                'tags' => ['triceps', 'barra', 'banco', 'aislamiento'],
            ],

            // ========== ABS / CORE ==========
            [
                'name' => 'Plank',
                'name_es' => 'Plancha abdominal',
                'description' => 'Static core stability exercise',
                'description_es' => 'Ejercicio isométrico fundamental para la estabilidad del core.',
                'primary_muscle_group' => 'Abs',
                'muscle_groups' => ['Abs', 'Lower Back', 'Shoulders'],
                'equipment' => 'Bodyweight',
                'difficulty' => 'beginner',
                'location_type' => 'both',
                'exercise_type' => 'strength',
                'calories_per_minute' => 4.0,
                'met_value' => 3.8,
                'is_compound' => false,
                'instructions' => [
                    'Apoya los antebrazos en el suelo con los codos bajo los hombros',
                    'Extiende las piernas hacia atrás apoyando en las puntas de los pies',
                    'El cuerpo debe formar una línea recta de cabeza a talones',
                    'Aprieta el core, los glúteos y los cuádriceps',
                    'Mantén la posición respirando de forma constante',
                ],
                'tips' => [
                    'No dejes caer las caderas ni elevarlas demasiado',
                    'Mira hacia el suelo para mantener el cuello neutral',
                ],
                'tags' => ['abdominales', 'core', 'isométrico', 'sin equipo', 'casa'],
            ],
            [
                'name' => 'Crunch',
                'name_es' => 'Crunch abdominal',
                'description' => 'Basic abdominal exercise targeting rectus abdominis',
                'description_es' => 'Ejercicio básico para el recto abdominal.',
                'primary_muscle_group' => 'Abs',
                'muscle_groups' => ['Abs'],
                'equipment' => 'Bodyweight',
                'difficulty' => 'beginner',
                'location_type' => 'both',
                'exercise_type' => 'strength',
                'calories_per_minute' => 4.5,
                'met_value' => 4.0,
                'is_compound' => false,
                'instructions' => [
                    'Túmbate boca arriba con las rodillas flexionadas y pies en el suelo',
                    'Manos detrás de la cabeza sin tirar del cuello',
                    'Contrae el abdomen elevando los hombros del suelo',
                    'La parte baja de la espalda permanece en contacto con el suelo',
                    'Baja de forma controlada sin llegar a apoyar la cabeza',
                ],
                'tips' => [
                    'No tires del cuello con las manos',
                    'El movimiento debe ser corto y controlado',
                ],
                'tags' => ['abdominales', 'recto abdominal', 'sin equipo', 'casa'],
            ],
            [
                'name' => 'Bicycle Crunch',
                'name_es' => 'Crunch bicicleta',
                'description' => 'Dynamic core exercise targeting obliques',
                'description_es' => 'Crunch dinámico para trabajar los oblicuos y el recto abdominal.',
                'primary_muscle_group' => 'Abs',
                'muscle_groups' => ['Abs', 'Obliques'],
                'equipment' => 'Bodyweight',
                'difficulty' => 'beginner',
                'location_type' => 'both',
                'exercise_type' => 'strength',
                'calories_per_minute' => 6.0,
                'met_value' => 5.5,
                'is_compound' => false,
                'instructions' => [
                    'Túmbate boca arriba con las manos detrás de la cabeza',
                    'Eleva las piernas del suelo con las rodillas dobladas a 90 grados',
                    'Lleva el codo derecho hacia la rodilla izquierda mientras extiendes la pierna derecha',
                    'Alterna el movimiento como si pedalearas en una bicicleta',
                ],
                'tips' => [
                    'Controla el movimiento, no vayas demasiado rápido',
                    'Rota desde el torso, no desde el cuello',
                ],
                'tags' => ['abdominales', 'oblicuos', 'sin equipo', 'casa'],
            ],
            [
                'name' => 'Leg Raise',
                'name_es' => 'Elevación de piernas',
                'description' => 'Lower abs exercise performed lying down',
                'description_es' => 'Ejercicio para el abdomen inferior tumbado boca arriba.',
                'primary_muscle_group' => 'Abs',
                'muscle_groups' => ['Abs', 'Hip Flexors'],
                'equipment' => 'Bodyweight',
                'difficulty' => 'intermediate',
                'location_type' => 'both',
                'exercise_type' => 'strength',
                'calories_per_minute' => 5.5,
                'met_value' => 4.5,
                'is_compound' => false,
                'instructions' => [
                    'Túmbate boca arriba con las piernas extendidas',
                    'Manos a los lados del cuerpo o bajo los glúteos',
                    'Eleva las piernas juntas hasta formar 90 grados con el torso',
                    'Baja de forma controlada sin que los talones toquen el suelo',
                ],
                'tips' => [
                    'Si es muy difícil, dobla ligeramente las rodillas',
                    'Presiona la espalda baja contra el suelo durante todo el movimiento',
                ],
                'tags' => ['abdominales', 'abdomen inferior', 'sin equipo', 'casa'],
            ],
            [
                'name' => 'Mountain Climber',
                'name_es' => 'Escalador',
                'description' => 'Dynamic full body exercise with cardio component',
                'description_es' => 'Ejercicio dinámico de cuerpo completo con componente cardiovascular.',
                'primary_muscle_group' => 'Abs',
                'muscle_groups' => ['Abs', 'Shoulders', 'Hip Flexors'],
                'equipment' => 'Bodyweight',
                'difficulty' => 'intermediate',
                'location_type' => 'both',
                'exercise_type' => 'functional',
                'calories_per_minute' => 10.0,
                'met_value' => 8.0,
                'is_compound' => true,
                'instructions' => [
                    'Comienza en posición de plancha alta con los brazos extendidos',
                    'Lleva la rodilla derecha hacia el pecho de forma explosiva',
                    'Vuelve a la posición inicial y repite con la pierna izquierda',
                    'Alterna rápidamente como si escalaras una montaña horizontal',
                ],
                'tips' => [
                    'Mantén las caderas abajo y el core apretado',
                    'Puedes hacerlo más lento para mayor énfasis en el core',
                ],
                'tags' => ['abdominales', 'cardio', 'sin equipo', 'casa', 'HIIT'],
            ],

            // ========== CARDIO / FULL BODY ==========
            [
                'name' => 'Burpee',
                'name_es' => 'Burpee',
                'description' => 'High-intensity full body exercise combining squat, push-up and jump',
                'description_es' => 'Ejercicio de alta intensidad que combina sentadilla, flexión y salto. Uno de los más completos.',
                'primary_muscle_group' => 'Full Body',
                'muscle_groups' => ['Full Body', 'Chest', 'Quadriceps', 'Abs'],
                'equipment' => 'Bodyweight',
                'difficulty' => 'intermediate',
                'location_type' => 'both',
                'exercise_type' => 'hiit',
                'calories_per_minute' => 12.0,
                'met_value' => 10.0,
                'is_compound' => true,
                'instructions' => [
                    'De pie, baja en cuclillas y apoya las manos en el suelo',
                    'Salta los pies hacia atrás quedando en posición de plancha alta',
                    'Realiza una flexión completa',
                    'Salta los pies hacia adelante volviendo a la posición de cuclillas',
                    'Salta verticalmente elevando los brazos por encima de la cabeza',
                ],
                'tips' => [
                    'Para principiantes, elimina el salto y la flexión',
                    'Mantén un ritmo constante en lugar de ir muy rápido y agotarte',
                ],
                'tags' => ['cuerpo completo', 'cardio', 'HIIT', 'sin equipo', 'casa'],
            ],
            [
                'name' => 'Jumping Jack',
                'name_es' => 'Salto estrella',
                'description' => 'Classic warm-up cardio exercise',
                'description_es' => 'Ejercicio clásico de calentamiento cardiovascular.',
                'primary_muscle_group' => 'Cardio',
                'muscle_groups' => ['Full Body', 'Cardio'],
                'equipment' => 'Bodyweight',
                'difficulty' => 'beginner',
                'location_type' => 'both',
                'exercise_type' => 'cardio',
                'calories_per_minute' => 8.0,
                'met_value' => 7.5,
                'is_compound' => true,
                'instructions' => [
                    'Párate con los pies juntos y los brazos a los lados',
                    'Salta abriendo las piernas al ancho de hombros y eleva los brazos por encima de la cabeza',
                    'Salta volviendo a la posición inicial',
                    'Repite a un ritmo constante',
                ],
                'tips' => [
                    'Usa calzado con amortiguación si lo haces durante mucho tiempo',
                    'Mantén las rodillas ligeramente flexionadas al aterrizar',
                ],
                'tags' => ['cardio', 'calentamiento', 'sin equipo', 'casa'],
            ],
            [
                'name' => 'Box Jump',
                'name_es' => 'Salto al cajón',
                'description' => 'Plyometric exercise for explosive power',
                'description_es' => 'Ejercicio pliométrico para desarrollar potencia explosiva en el tren inferior.',
                'primary_muscle_group' => 'Quadriceps',
                'muscle_groups' => ['Quadriceps', 'Glutes', 'Calves'],
                'equipment' => 'Box / Plyo Box',
                'difficulty' => 'intermediate',
                'location_type' => 'gym',
                'exercise_type' => 'plyometric',
                'calories_per_minute' => 12.0,
                'met_value' => 10.0,
                'is_compound' => true,
                'instructions' => [
                    'Párate frente al cajón a una distancia cómoda',
                    'Flexiona ligeramente las rodillas y los brazos hacia atrás',
                    'Salta explosivamente sobre el cajón usando el impulso de brazos',
                    'Aterriza con ambos pies planos sobre el cajón, rodillas flexionadas',
                    'Baja del cajón de forma controlada (o salta hacia atrás)',
                ],
                'tips' => [
                    'Comienza con un cajón de poca altura y ve aumentando',
                    'El aterrizaje debe ser suave, nunca rígido',
                ],
                'tags' => ['pliometria', 'cuadriceps', 'gluteos', 'potencia', 'gym'],
            ],
            [
                'name' => 'Kettlebell Swing',
                'name_es' => 'Balanceo con pesa rusa',
                'description' => 'Dynamic hip hinge movement for posterior chain and cardio',
                'description_es' => 'Movimiento dinámico con pesa rusa para cadena posterior y acondicionamiento cardiovascular.',
                'primary_muscle_group' => 'Glutes',
                'muscle_groups' => ['Glutes', 'Hamstrings', 'Back', 'Abs'],
                'equipment' => 'Kettlebell',
                'difficulty' => 'intermediate',
                'location_type' => 'both',
                'exercise_type' => 'functional',
                'calories_per_minute' => 13.0,
                'met_value' => 10.3,
                'is_compound' => true,
                'instructions' => [
                    'Párate con los pies algo más abiertos que el ancho de hombros',
                    'Agarra la kettlebell con ambas manos, agarre prono',
                    'Inclínate hacia adelante con la cadera y columpia la kettlebell entre las piernas',
                    'Empuja las caderas hacia adelante explosivamente para impulsarla hacia arriba',
                    'La kettlebell sube hasta la altura del pecho por el impulso de caderas',
                    'Deja que vuelva a oscilar entre las piernas y repite',
                ],
                'tips' => [
                    'El movimiento viene de las caderas, no de los brazos ni la espalda',
                    'Aprieta los glúteos y el core al extender las caderas',
                ],
                'tags' => ['pesa rusa', 'cadena posterior', 'cardio', 'funcional'],
            ],
            [
                'name' => 'Wall Sit',
                'name_es' => 'Sentadilla en pared',
                'description' => 'Isometric leg exercise against a wall',
                'description_es' => 'Ejercicio isométrico de cuádriceps contra la pared.',
                'primary_muscle_group' => 'Quadriceps',
                'muscle_groups' => ['Quadriceps', 'Glutes'],
                'equipment' => 'Bodyweight',
                'difficulty' => 'beginner',
                'location_type' => 'both',
                'exercise_type' => 'strength',
                'calories_per_minute' => 4.5,
                'met_value' => 3.5,
                'is_compound' => false,
                'instructions' => [
                    'Apoya la espalda contra la pared y camina los pies hacia adelante',
                    'Desliza la espalda hacia abajo hasta que las rodillas formen 90 grados',
                    'Los pies deben estar planos en el suelo, directamente bajo las rodillas',
                    'Mantén la posición con el core apretado y la espalda pegada a la pared',
                ],
                'tips' => [
                    'Si sientes dolor en las rodillas, sube ligeramente la posición',
                    'Añade un tiempo objetivo y ve aumentándolo',
                ],
                'tags' => ['cuadriceps', 'isométrico', 'sin equipo', 'casa'],
            ],
            [
                'name' => 'Goblet Squat',
                'name_es' => 'Sentadilla goblet',
                'description' => 'Front-loaded squat variation with kettlebell or dumbbell',
                'description_es' => 'Variante de sentadilla con peso al frente. Excelente para la técnica.',
                'primary_muscle_group' => 'Quadriceps',
                'muscle_groups' => ['Quadriceps', 'Glutes', 'Abs'],
                'equipment' => 'Kettlebell',
                'difficulty' => 'beginner',
                'location_type' => 'both',
                'exercise_type' => 'strength',
                'calories_per_minute' => 8.0,
                'met_value' => 6.0,
                'is_compound' => true,
                'instructions' => [
                    'Sujeta la kettlebell por el cuello con ambas manos a la altura del pecho',
                    'Los pies algo más abiertos que el ancho de hombros',
                    'Baja en sentadilla manteniendo el peso bien sujeto al pecho',
                    'Los codos deben pasar por el interior de las rodillas en la posición inferior',
                    'Sube empujando el suelo con los pies',
                ],
                'tips' => [
                    'El peso al frente te ayuda a mantener el torso vertical',
                    'Ideal para aprender la técnica de sentadilla',
                ],
                'tags' => ['cuadriceps', 'gluteos', 'pesa rusa', 'mancuerna', 'técnica'],
            ],
            [
                'name' => 'Superman',
                'name_es' => 'Superman',
                'description' => 'Back extension exercise for lower back strength',
                'description_es' => 'Ejercicio para fortalecer la zona lumbar en posición tumbado boca abajo.',
                'primary_muscle_group' => 'Lower Back',
                'muscle_groups' => ['Lower Back', 'Glutes'],
                'equipment' => 'Bodyweight',
                'difficulty' => 'beginner',
                'location_type' => 'both',
                'exercise_type' => 'strength',
                'calories_per_minute' => 3.5,
                'met_value' => 3.0,
                'is_compound' => false,
                'instructions' => [
                    'Túmbate boca abajo con los brazos extendidos por encima de la cabeza',
                    'Eleva simultáneamente los brazos y las piernas del suelo',
                    'Aprieta los glúteos y los músculos de la espalda',
                    'Mantén 1-2 segundos en la posición superior',
                    'Baja de forma controlada',
                ],
                'tips' => [
                    'No fuerces el cuello, mira hacia el suelo',
                    'El movimiento debe ser controlado, no explosivo',
                ],
                'tags' => ['lumbar', 'gluteos', 'sin equipo', 'casa', 'rehabilitación'],
            ],
            [
                'name' => 'Russian Twist',
                'name_es' => 'Giro ruso',
                'description' => 'Rotational core exercise for obliques',
                'description_es' => 'Ejercicio rotacional para oblicuos y abdominales.',
                'primary_muscle_group' => 'Obliques',
                'muscle_groups' => ['Obliques', 'Abs'],
                'equipment' => 'Bodyweight',
                'difficulty' => 'beginner',
                'location_type' => 'both',
                'exercise_type' => 'strength',
                'calories_per_minute' => 5.5,
                'met_value' => 4.5,
                'is_compound' => false,
                'instructions' => [
                    'Siéntate en el suelo con las rodillas flexionadas y los pies elevados',
                    'Inclínate ligeramente hacia atrás manteniendo la espalda recta',
                    'Con las manos juntas, gira el torso hacia la derecha',
                    'Vuelve al centro y gira hacia la izquierda',
                    'Mantén el core apretado durante todo el movimiento',
                ],
                'tips' => [
                    'Para hacerlo más difícil, sostén un balón medicinal o mancuerna',
                    'Para principiantes, mantén los pies en el suelo',
                ],
                'tags' => ['oblicuos', 'abdominales', 'sin equipo', 'casa'],
            ],
            [
                'name' => 'Dumbbell Row',
                'name_es' => 'Remo con mancuerna',
                'description' => 'Unilateral back exercise with dumbbell',
                'description_es' => 'Remo unilateral con mancuerna para el grosor de la espalda.',
                'primary_muscle_group' => 'Back',
                'muscle_groups' => ['Back', 'Lats', 'Biceps'],
                'equipment' => 'Dumbbells',
                'difficulty' => 'beginner',
                'location_type' => 'both',
                'exercise_type' => 'strength',
                'calories_per_minute' => 6.5,
                'met_value' => 5.0,
                'is_compound' => true,
                'instructions' => [
                    'Apoya la rodilla izquierda y la mano izquierda en el banco',
                    'La espalda paralela al suelo, la derecha mano sostiene la mancuerna',
                    'Tira de la mancuerna hacia la cadera retrayendo la escápula',
                    'Baja de forma controlada hasta la extensión completa',
                    'Repite con el otro brazo',
                ],
                'tips' => [
                    'No rotes el torso para levantar el peso',
                    'El codo debe moverse pegado al cuerpo y hacia atrás',
                ],
                'tags' => ['espalda', 'mancuerna', 'unilateral', 'remo'],
            ],
            [
                'name' => 'Face Pull',
                'name_es' => 'Jalón a la cara',
                'description' => 'Cable exercise for rear deltoids and rotator cuff',
                'description_es' => 'Ejercicio con polea para deltoides posterior y manguito rotador. Excelente para la salud de los hombros.',
                'primary_muscle_group' => 'Shoulders',
                'muscle_groups' => ['Shoulders', 'Trapezius', 'Back'],
                'equipment' => 'Cable Machine',
                'difficulty' => 'beginner',
                'location_type' => 'gym',
                'exercise_type' => 'strength',
                'calories_per_minute' => 5.0,
                'met_value' => 4.0,
                'is_compound' => false,
                'instructions' => [
                    'Configura la polea alta con una cuerda de doble mango',
                    'Párate frente a la máquina a distancia que permita tensión con brazos extendidos',
                    'Agarra cada lado de la cuerda y tira hacia la cara',
                    'Los codos deben estar elevados y moverse hacia atrás',
                    'Separa las manos y lleva las palmas hacia afuera al final del movimiento',
                ],
                'tips' => [
                    'Este ejercicio es fundamental para la salud de los hombros',
                    'Hazlo con peso moderado y alto número de repeticiones',
                ],
                'tags' => ['hombros', 'deltoides posterior', 'salud', 'polea'],
            ],
            [
                'name' => 'Step-up',
                'name_es' => 'Subida al cajón',
                'description' => 'Unilateral leg exercise using a box or bench',
                'description_es' => 'Ejercicio unilateral de piernas con cajón o banco.',
                'primary_muscle_group' => 'Quadriceps',
                'muscle_groups' => ['Quadriceps', 'Glutes', 'Hamstrings'],
                'equipment' => 'Box / Plyo Box',
                'difficulty' => 'beginner',
                'location_type' => 'both',
                'exercise_type' => 'strength',
                'calories_per_minute' => 7.0,
                'met_value' => 6.0,
                'is_compound' => true,
                'instructions' => [
                    'Párate frente a un cajón o banco estable',
                    'Coloca el pie derecho sobre el cajón',
                    'Empuja con el pie derecho para subir todo el cuerpo',
                    'Lleva el pie izquierdo al cajón y después baja el pie derecho',
                    'Alterna la pierna de inicio o completa las repeticiones con una pierna antes de cambiar',
                ],
                'tips' => [
                    'La pierna que está en el cajón hace todo el trabajo',
                    'Evita empujar con la pierna que está en el suelo',
                ],
                'tags' => ['cuadriceps', 'gluteos', 'unilateral', 'funcional'],
            ],
            [
                'name' => 'Dips (Bench)',
                'name_es' => 'Fondos en banco',
                'description' => 'Tricep dips using a bench for beginners',
                'description_es' => 'Fondos de tríceps con banco, ideal para principiantes y en casa.',
                'primary_muscle_group' => 'Triceps',
                'muscle_groups' => ['Triceps', 'Chest'],
                'equipment' => 'Bodyweight',
                'difficulty' => 'beginner',
                'location_type' => 'both',
                'exercise_type' => 'strength',
                'calories_per_minute' => 6.5,
                'met_value' => 5.5,
                'is_compound' => false,
                'instructions' => [
                    'Siéntate en el borde de un banco o silla sólida',
                    'Apoya las manos en el borde del banco, dedos hacia adelante',
                    'Desliza los glúteos hacia adelante levantándote del banco',
                    'Baja el cuerpo flexionando los codos hasta 90 grados',
                    'Empuja hacia arriba extendiendo los codos',
                ],
                'tips' => [
                    'Mantén los codos hacia atrás, no hacia los lados',
                    'Para hacerlo más difícil, eleva los pies',
                ],
                'tags' => ['triceps', 'sin equipo', 'casa', 'principiante'],
            ],
            [
                'name' => 'Incline Push-up',
                'name_es' => 'Flexión inclinada',
                'description' => 'Easier push-up variation with hands elevated',
                'description_es' => 'Flexión facilitada con las manos elevadas. Ideal para principiantes.',
                'primary_muscle_group' => 'Chest',
                'muscle_groups' => ['Chest', 'Triceps', 'Shoulders'],
                'equipment' => 'Bodyweight',
                'difficulty' => 'beginner',
                'location_type' => 'both',
                'exercise_type' => 'strength',
                'calories_per_minute' => 5.5,
                'met_value' => 5.0,
                'is_compound' => true,
                'instructions' => [
                    'Coloca las manos en una superficie elevada (banco, escalón)',
                    'Las manos ligeramente más separadas que los hombros',
                    'El cuerpo en línea recta',
                    'Baja el pecho hacia la superficie de apoyo',
                    'Empuja hasta la extensión',
                ],
                'tips' => [
                    'Cuanto más alta la superficie, más fácil el ejercicio',
                    'Progresa hacia flexiones en el suelo cuando puedas',
                ],
                'tags' => ['pecho', 'principiante', 'sin equipo', 'casa'],
            ],
            [
                'name' => 'Decline Push-up',
                'name_es' => 'Flexión declinada',
                'description' => 'Advanced push-up with feet elevated targeting upper chest',
                'description_es' => 'Flexión avanzada con los pies elevados para enfatizar el pecho superior.',
                'primary_muscle_group' => 'Chest',
                'muscle_groups' => ['Chest', 'Shoulders', 'Triceps'],
                'equipment' => 'Bodyweight',
                'difficulty' => 'advanced',
                'location_type' => 'both',
                'exercise_type' => 'strength',
                'calories_per_minute' => 9.0,
                'met_value' => 9.0,
                'is_compound' => true,
                'instructions' => [
                    'Coloca los pies en una superficie elevada (banco, silla)',
                    'Las manos en el suelo ligeramente más anchas que los hombros',
                    'El cuerpo en línea recta desde cabeza a talones',
                    'Baja el pecho hacia el suelo',
                    'Empuja hasta la extensión completa',
                ],
                'tips' => [
                    'Cuanto más elevados los pies, más difícil y más énfasis en el pecho superior',
                    'Mantén el core muy apretado',
                ],
                'tags' => ['pecho', 'avanzado', 'sin equipo', 'casa'],
            ],
            [
                'name' => 'Pike Push-up',
                'name_es' => 'Flexión en pica',
                'description' => 'Shoulder-targeting push-up variation',
                'description_es' => 'Variante de flexión que imita el press militar para desarrollar hombros.',
                'primary_muscle_group' => 'Shoulders',
                'muscle_groups' => ['Shoulders', 'Triceps'],
                'equipment' => 'Bodyweight',
                'difficulty' => 'intermediate',
                'location_type' => 'both',
                'exercise_type' => 'strength',
                'calories_per_minute' => 7.5,
                'met_value' => 7.0,
                'is_compound' => true,
                'instructions' => [
                    'Empieza en posición de flexión y camina las manos hacia los pies',
                    'Eleva las caderas hasta formar una V invertida',
                    'Baja la cabeza hacia el suelo entre las manos flexionando los codos',
                    'Empuja hacia arriba hasta la extensión',
                ],
                'tips' => [
                    'Cuanto más vertical tu cuerpo, más trabajan los hombros',
                    'Progresión hacia la flexión vertical (handstand push-up)',
                ],
                'tags' => ['hombros', 'sin equipo', 'casa', 'calistenia'],
            ],
        ];

        foreach ($exercises as $exerciseData) {
            $primaryMuscleGroupId = $muscleGroups[$exerciseData['primary_muscle_group']]->id ?? null;
            $equipmentId = $equipment[$exerciseData['equipment']]->id ?? null;

            // Convert muscle group names to IDs
            $muscleGroupIds = array_values(array_filter(
                array_map(fn($name) => $muscleGroups[$name]->id ?? null, $exerciseData['muscle_groups']),
                fn($id) => $id !== null
            ));

            Exercise::updateOrCreate(
                ['name' => $exerciseData['name']],
                [
                    'name_es' => $exerciseData['name_es'],
                    'description' => $exerciseData['description'],
                    'description_es' => $exerciseData['description_es'],
                    'primary_muscle_group_id' => $primaryMuscleGroupId,
                    'muscle_groups' => $muscleGroupIds,
                    'equipment_id' => $equipmentId,
                    'difficulty' => $exerciseData['difficulty'],
                    'location_type' => $exerciseData['location_type'],
                    'exercise_type' => $exerciseData['exercise_type'],
                    'calories_per_minute' => $exerciseData['calories_per_minute'],
                    'met_value' => $exerciseData['met_value'],
                    'is_compound' => $exerciseData['is_compound'],
                    'instructions' => $exerciseData['instructions'],
                    'tips' => $exerciseData['tips'] ?? [],
                    'tags' => $exerciseData['tags'],
                    'is_public' => true,
                    'is_active' => true,
                ]
            );
        }

        $this->command->info('Exercises seeded successfully: ' . count($exercises) . ' exercises created.');
    }
}
